[package]
name = "match-planner"
version = "0.2.0"
authors = ["Fabian Thorand <f.thorand@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
itertools = "0.8.1"
structopt = "0.3.3"
csv = "1.1.1"
ndarray = "0.13.0"
